# Generated by Django 2.0.2 on 2018-04-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Project',
        ),
    ]
