# Generated by Django 2.0.2 on 2018-04-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20180413_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
