# Generated by Django 2.0.2 on 2018-04-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_auto_20180417_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
